export const locales=['fa','en'] as const;export type Locale=typeof locales[number];
export const dict={fa:{dir:'rtl',brand:'TripNest',admin:'پنل ادمین',lang:'EN',hero:'TripNest Enterprise Offline V26',sub:'سوپر اپ سفر برای برنامه‌ریزی چندروزه، هتل، پرواز، تور، راهنمای محلی، همسفر، بلاگ، پروفایل، ووچر و پنل مدیریت کامل.',cta:'شروع برنامه‌ریزی سفر',search:'جستجوی شهر، هتل یا لوکیشن',nav:['هتل‌ها','پرواز','تور','برنامه سفر','راهنما','همسفر','بلاگ']},en:{dir:'ltr',brand:'TripNest',admin:'Admin',lang:'FA',hero:'TripNest Enterprise Offline V26',sub:'A complete travel super app for itineraries, hotels, flights, tours, local guides, travel mate, blog, profile, voucher and admin CMS.',cta:'Start planning',search:'Search city, hotel or location',nav:['Hotels','Flights','Tours','Itinerary','Guides','Mate','Blog']}} as const;
export const nav=[['hotels','هتل‌ها','Hotels'],['flights','پرواز','Flights'],['tours','تور','Tours'],['itinerary','برنامه سفر','Itinerary'],['guides','راهنما','Guides'],['travel-mate','همسفر','Mate'],['blog','بلاگ','Blog']];
export const cities=[{fa:'تهران',en:'Tehran',tag:'Business',hotels:128,cover:'https://images.unsplash.com/photo-1518005020951-eccb494ad742?q=80&w=1200'},{fa:'مشهد',en:'Mashhad',tag:'Pilgrimage',hotels:210,cover:'https://images.unsplash.com/photo-1548013146-72479768bada?q=80&w=1200'},{fa:'شیراز',en:'Shiraz',tag:'Culture',hotels:86,cover:'https://images.unsplash.com/photo-1589302168068-964664d93dc0?q=80&w=1200'},{fa:'کیش',en:'Kish',tag:'Leisure',hotels:74,cover:'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?q=80&w=1200'},{fa:'استانبول',en:'Istanbul',tag:'International',hotels:340,cover:'https://images.unsplash.com/photo-1524231757912-21f4fe3a7200?q=80&w=1200'}];
export const hotels=[{name:'هتل هما شیراز',city:'شیراز',grade:'5 ستاره',price:4800000,score:9.1,provider:'IHO Provider',status:'Online',features:['صبحانه','کنسلی منعطف','ووچر آنی']},{name:'هتل درویشی مشهد',city:'مشهد',grade:'5 ستاره',price:6200000,score:9.3,provider:'NetMinder',status:'Liveable',features:['نزدیک حرم','ظرفیت لحظه‌ای','VIP']},{name:'هتل اسپیناس پالاس',city:'تهران',grade:'5 ستاره',price:7900000,score:9.4,provider:'Lamasoo',status:'Online',features:['بیزینسی','لوکس','پرداخت اقساطی']},{name:'هتل داریوش کیش',city:'کیش',grade:'5 ستاره',price:8500000,score:9.2,provider:'Sepehr',status:'Online',features:['ساحلی','خانوادگی','تخفیف ویژه']},{name:'هتل پارسیان آزادی',city:'تهران',grade:'5 ستاره',price:5900000,score:8.9,provider:'IHO Provider',status:'Needs Capacity',features:['جلسات','مرکز شهر','B2B']}];
export const itineraries=[{title:'سفر ۳ روزه شیراز',city:'شیراز',days:['حافظیه، سعدیه، باغ ارم','تخت جمشید و نقش رستم','بازار وکیل و شاهچراغ'],budget:'اقتصادی تا لوکس'},{title:'مشهد زیارتی سریع',city:'مشهد',days:['ورود و حرم','طرقبه و شاندیز','خرید و بازگشت'],budget:'میان‌رده'},{title:'کیش تفریحی',city:'کیش',days:['ساحل و کشتی','غواصی و تفریحات','خرید و کافه'],budget:'لوکس'}];
export const guides=[{name:'سارا رضایی',city:'شیراز',skill:'تاریخ و فرهنگ',rate:4.9,price:'۱,۲۰۰,۰۰۰'},{name:'علی کریمی',city:'تهران',skill:'تور شهری و غذا',rate:4.7,price:'۹۵۰,۰۰۰'},{name:'مریم احمدی',city:'کیش',skill:'تفریحات دریایی',rate:4.8,price:'۱,۵۰۰,۰۰۰'}];
export const flights=[{from:'تهران',to:'مشهد',time:'08:30',price:'۲,۴۵۰,۰۰۰',airline:'TripNest Air'},{from:'تهران',to:'شیراز',time:'12:10',price:'۲,۹۰۰,۰۰۰',airline:'Pars Flight'},{from:'مشهد',to:'کیش',time:'19:40',price:'۳,۸۰۰,۰۰۰',airline:'Iran Sky'}];
export const tours=[{title:'تور شیراز فرهنگی',days:3,price:'۹,۸۰۰,۰۰۰',type:'Culture'},{title:'تور کیش لوکس',days:4,price:'۱۸,۵۰۰,۰۰۰',type:'Luxury'},{title:'تور استانبول خرید',days:5,price:'۲۹,۰۰۰,۰۰۰',type:'International'}];
export const posts=[{slug:'iran-travel-superapp',title:'چرا بازار ایران به سوپر اپ سفر نیاز دارد؟',cat:'Product'},{slug:'hotel-provider-connectivity',title:'اتصال پروایدرها و ظرفیت آنلاین هتل‌ها',cat:'Hotel Tech'},{slug:'trip-planner-ai',title:'برنامه‌ساز سفر هوشمند چگونه کار می‌کند؟',cat:'AI'}];
export const admin=[['Hotels','۳۵۰۰','نرخ، ظرفیت، وضعیت همکاری، پروایدر منتخب، قرارداد'],['Bookings','۱۲,۸۴۰','رزرو، ووچر، کنسلی، پرداخت، کانفرم'],['Itineraries','۲۴۰','مسیرهای چندروزه، بودجه، جاذبه‌ها، SEO'],['Guides','۸۴','درخواست راهنمای محلی، قیمت، فعال/غیرفعال'],['CMS','۱۸۶','Hero، کارت‌ها، بنرها، FAQ، بلاگ'],['Users','۵۸,۰۰۰','پروفایل، علاقه‌مندی، همسفر، وفاداری']];
export const kpis=[['GMV','۱۲.۸B','+18%'],['Bookings','8,420','+9%'],['Live Hotels','2,438','+21%'],['Margin','14.6%','+0.8%']];
export function money(n:number){return new Intl.NumberFormat('fa-IR').format(n)+' تومان'}
