export const locales=['fa','en'] as const; export type Locale=typeof locales[number];
export const t={fa:{lang:'EN',admin:'پنل مدیریت',profile:'پروفایل',cta:'شروع برنامه‌ریزی',search:'شهر، هتل، جاذبه یا مقصد را جستجو کن',hero:'سوپر اپ کامل سفر برای بازار ایران و توسعه بین‌المللی',sub:'TripNest یک محصول واقعی است: رزرو هتل، پرواز، تور، برنامه‌ساز سفر، راهنمای محلی، همسفر، کیف پول، ووچر، CMS و پنل عملیات.'},en:{lang:'FA',admin:'Admin',profile:'Profile',cta:'Start planning',search:'Search city, hotel, attraction or destination',hero:'A full travel super app for Iran and beyond',sub:'TripNest is a product-grade platform: hotels, flights, tours, itineraries, local guides, travel mate, wallet, vouchers, CMS and operations console.'}} as const;
export const nav=[['hotels','هتل‌ها','Hotels'],['flights','پرواز','Flights'],['tours','تور','Tours'],['itinerary','برنامه سفر','Itinerary'],['guides','راهنما','Guides'],['travel-mate','همسفر','Travel Mate'],['blog','بلاگ','Blog']];
export const cities=[{fa:'تهران',en:'Tehran',tag:'Business',hotels:428,demand:91,img:'https://images.unsplash.com/photo-1518005020951-eccb494ad742?q=80&w=1200'},{fa:'مشهد',en:'Mashhad',tag:'Pilgrimage',hotels:612,demand:98,img:'https://images.unsplash.com/photo-1548013146-72479768bada?q=80&w=1200'},{fa:'شیراز',en:'Shiraz',tag:'Culture',hotels:184,demand:86,img:'https://images.unsplash.com/photo-1589302168068-964664d93dc0?q=80&w=1200'},{fa:'کیش',en:'Kish',tag:'Leisure',hotels:156,demand:88,img:'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?q=80&w=1200'},{fa:'استانبول',en:'Istanbul',tag:'International',hotels:820,demand:94,img:'https://images.unsplash.com/photo-1524231757912-21f4fe3a7200?q=80&w=1200'}];
export const hotels=[{name:'هتل هما شیراز',city:'شیراز',grade:'5★',price:4800000,score:9.1,provider:'IHO Provider',status:'Online',margin:'16%',tags:['خانوادگی','کنسلی منعطف','ووچر آنی']},{name:'هتل درویشی مشهد',city:'مشهد',grade:'5★',price:6200000,score:9.3,provider:'NetMinder',status:'Liveable',margin:'18%',tags:['نزدیک حرم','ظرفیت لحظه‌ای','VIP']},{name:'اسپیناس پالاس',city:'تهران',grade:'5★',price:7900000,score:9.4,provider:'Lamasoo',status:'Online',margin:'13%',tags:['بیزینسی','لوکس','اقساطی']},{name:'داریوش کیش',city:'کیش',grade:'5★',price:8500000,score:9.2,provider:'Sepehr',status:'Online',margin:'15%',tags:['ساحلی','تفریحی','تخفیف']},{name:'پارسیان آزادی',city:'تهران',grade:'5★',price:5900000,score:8.9,provider:'IHO Provider',status:'Need Capacity',margin:'12%',tags:['جلسات','مرکز شهر','B2B']},{name:'هتل اطلس مشهد',city:'مشهد',grade:'4★',price:3100000,score:8.4,provider:'Adotel',status:'Offline Risk',margin:'10%',tags:['اقتصادی','زیارتی','پرتقاضا']}];
export const flights=[{from:'تهران',to:'مشهد',time:'08:30',airline:'TripNest Air',price:'۲,۴۵۰,۰۰۰',class:'اکونومی'},{from:'تهران',to:'شیراز',time:'12:10',airline:'Pars Flight',price:'۲,۹۰۰,۰۰۰',class:'اکونومی'},{from:'مشهد',to:'کیش',time:'19:40',airline:'Iran Sky',price:'۳,۸۰۰,۰۰۰',class:'بیزینس'}];
export const tours=[{title:'تور شیراز فرهنگی',days:3,price:'۹,۸۰۰,۰۰۰',type:'Culture',includes:['هتل','راهنما','گشت شهری']},{title:'تور کیش لوکس',days:4,price:'۱۸,۵۰۰,۰۰۰',type:'Luxury',includes:['پرواز','هتل ۵ ستاره','تفریحات']},{title:'تور استانبول خرید',days:5,price:'۲۹,۰۰۰,۰۰۰',type:'International',includes:['پرواز','هتل','ترانسفر']}];
export const itineraries=[{title:'شیراز ۳ روزه',budget:'میان‌رده',days:['حافظیه، سعدیه، باغ ارم','تخت جمشید و نقش رستم','بازار وکیل، شاهچراغ، کافه‌گردی']},{title:'مشهد زیارتی سریع',budget:'اقتصادی',days:['ورود، حرم، بازار رضا','طرقبه و شاندیز','خرید و بازگشت']},{title:'کیش تفریحی',budget:'لوکس',days:['ساحل و کشتی','غواصی و تفریحات','خرید و کافه']}];
export const guides=[{name:'سارا رضایی',city:'شیراز',skill:'تاریخ و فرهنگ',rate:4.9,price:'۱,۲۰۰,۰۰۰'},{name:'علی کریمی',city:'تهران',skill:'تور شهری و غذا',rate:4.7,price:'۹۵۰,۰۰۰'},{name:'مریم احمدی',city:'کیش',skill:'تفریحات دریایی',rate:4.8,price:'۱,۵۰۰,۰۰۰'}];
export const mates=[{name:'نیما',route:'تهران → شیراز',style:'فرهنگی و اقتصادی',date:'۲۸ خرداد'},{name:'رها',route:'مشهد → کیش',style:'تفریحی و خانوادگی',date:'۳ تیر'},{name:'سامان',route:'تهران → استانبول',style:'خرید و شهری',date:'۱۵ تیر'}];
export const posts=[{slug:'superapp',title:'چرا بازار ایران به سوپر اپ سفر نیاز دارد؟',cat:'Product'},{slug:'providers',title:'اتصال پروایدرها و ظرفیت آنلاین هتل‌ها',cat:'Hotel Tech'},{slug:'ai-trip',title:'برنامه‌ساز سفر هوشمند چگونه کار می‌کند؟',cat:'AI'}];
export const kpis=[['GMV','۱۲.۸B','+18%'],['Bookings','8,420','+9%'],['Live Hotels','2,438','+21%'],['Margin','14.6%','+0.8%']];
export const adminModules=[['Supply OS','۳۵۰۰ هتل','نرخ، ظرفیت، قرارداد، پروایدر منتخب و ریسک همکاری'],['Booking Ops','۱۲,۸۴۰ رزرو','کانفرم، ووچر، کنسلی، پرداخت و SLA'],['CMS Studio','۱۸۶ محتوا','Hero، بنر، کارت مقصد، FAQ، بلاگ و SEO'],['Growth CRM','۵۸K کاربر','سگمنت، کد تخفیف، پیامک، وفاداری و RFM'],['Guide Hub','۸۴ راهنما','فعال‌سازی راهنما، نرخ، امتیاز و درخواست‌ها'],['Finance','۱۴.۶٪ مارجین','تسویه، کمیسیون، کیف پول و گزارش مالی']];
export const roadmap=[['MVP+', 'Offline demo, PWA, bilingual, admin'],['Production', 'Auth, DB, payment, provider connectors'],['Scale', 'microservices, BI, personalization, loyalty'],['AI Layer', 'trip planner, smart pricing, supply risk scoring']];
export function money(n:number){return new Intl.NumberFormat('fa-IR').format(n)+' تومان'}
